/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteRouteImport } from './routes/gallery/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as QueueIndexRouteImport } from './routes/queue/index'
import { Route as MetadataIndexRouteImport } from './routes/metadata/index'
import { Route as GenerateIndexRouteImport } from './routes/generate/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as BundlesIndexRouteImport } from './routes/bundles/index'
import { Route as GalleryImageIdRouteImport } from './routes/gallery/$imageId'
import { Route as WorkspaceProjectIdRouteRouteImport } from './routes/workspace/$projectId/route'
import { Route as WorkspaceProjectIdIndexRouteImport } from './routes/workspace/$projectId/index'
import { Route as WorkspaceProjectIdScenesSceneIdRouteImport } from './routes/workspace/$projectId/scenes/$sceneId'

const GalleryRouteRoute = GalleryRouteRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataIndexRoute = MetadataIndexRouteImport.update({
  id: '/metadata/',
  path: '/metadata/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateIndexRoute = GenerateIndexRouteImport.update({
  id: '/generate/',
  path: '/generate/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GalleryRouteRoute,
} as any)
const BundlesIndexRoute = BundlesIndexRouteImport.update({
  id: '/bundles/',
  path: '/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryImageIdRoute = GalleryImageIdRouteImport.update({
  id: '/$imageId',
  path: '/$imageId',
  getParentRoute: () => GalleryRouteRoute,
} as any)
const WorkspaceProjectIdRouteRoute = WorkspaceProjectIdRouteRouteImport.update({
  id: '/workspace/$projectId',
  path: '/workspace/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectIdIndexRoute = WorkspaceProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceProjectIdRouteRoute,
} as any)
const WorkspaceProjectIdScenesSceneIdRoute =
  WorkspaceProjectIdScenesSceneIdRouteImport.update({
    id: '/scenes/$sceneId',
    path: '/scenes/$sceneId',
    getParentRoute: () => WorkspaceProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRouteRouteWithChildren
  '/workspace/$projectId': typeof WorkspaceProjectIdRouteRouteWithChildren
  '/gallery/$imageId': typeof GalleryImageIdRoute
  '/bundles/': typeof BundlesIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/generate/': typeof GenerateIndexRoute
  '/metadata/': typeof MetadataIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workspace/$projectId/': typeof WorkspaceProjectIdIndexRoute
  '/workspace/$projectId/scenes/$sceneId': typeof WorkspaceProjectIdScenesSceneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery/$imageId': typeof GalleryImageIdRoute
  '/bundles': typeof BundlesIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/generate': typeof GenerateIndexRoute
  '/metadata': typeof MetadataIndexRoute
  '/queue': typeof QueueIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workspace/$projectId': typeof WorkspaceProjectIdIndexRoute
  '/workspace/$projectId/scenes/$sceneId': typeof WorkspaceProjectIdScenesSceneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRouteRouteWithChildren
  '/workspace/$projectId': typeof WorkspaceProjectIdRouteRouteWithChildren
  '/gallery/$imageId': typeof GalleryImageIdRoute
  '/bundles/': typeof BundlesIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/generate/': typeof GenerateIndexRoute
  '/metadata/': typeof MetadataIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workspace/$projectId/': typeof WorkspaceProjectIdIndexRoute
  '/workspace/$projectId/scenes/$sceneId': typeof WorkspaceProjectIdScenesSceneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/workspace/$projectId'
    | '/gallery/$imageId'
    | '/bundles/'
    | '/gallery/'
    | '/generate/'
    | '/metadata/'
    | '/queue/'
    | '/settings/'
    | '/workspace/$projectId/'
    | '/workspace/$projectId/scenes/$sceneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery/$imageId'
    | '/bundles'
    | '/gallery'
    | '/generate'
    | '/metadata'
    | '/queue'
    | '/settings'
    | '/workspace/$projectId'
    | '/workspace/$projectId/scenes/$sceneId'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/workspace/$projectId'
    | '/gallery/$imageId'
    | '/bundles/'
    | '/gallery/'
    | '/generate/'
    | '/metadata/'
    | '/queue/'
    | '/settings/'
    | '/workspace/$projectId/'
    | '/workspace/$projectId/scenes/$sceneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRouteRoute: typeof GalleryRouteRouteWithChildren
  WorkspaceProjectIdRouteRoute: typeof WorkspaceProjectIdRouteRouteWithChildren
  BundlesIndexRoute: typeof BundlesIndexRoute
  GenerateIndexRoute: typeof GenerateIndexRoute
  MetadataIndexRoute: typeof MetadataIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata/': {
      id: '/metadata/'
      path: '/metadata'
      fullPath: '/metadata/'
      preLoaderRoute: typeof MetadataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/': {
      id: '/generate/'
      path: '/generate'
      fullPath: '/generate/'
      preLoaderRoute: typeof GenerateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof GalleryRouteRoute
    }
    '/bundles/': {
      id: '/bundles/'
      path: '/bundles'
      fullPath: '/bundles/'
      preLoaderRoute: typeof BundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$imageId': {
      id: '/gallery/$imageId'
      path: '/$imageId'
      fullPath: '/gallery/$imageId'
      preLoaderRoute: typeof GalleryImageIdRouteImport
      parentRoute: typeof GalleryRouteRoute
    }
    '/workspace/$projectId': {
      id: '/workspace/$projectId'
      path: '/workspace/$projectId'
      fullPath: '/workspace/$projectId'
      preLoaderRoute: typeof WorkspaceProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$projectId/': {
      id: '/workspace/$projectId/'
      path: '/'
      fullPath: '/workspace/$projectId/'
      preLoaderRoute: typeof WorkspaceProjectIdIndexRouteImport
      parentRoute: typeof WorkspaceProjectIdRouteRoute
    }
    '/workspace/$projectId/scenes/$sceneId': {
      id: '/workspace/$projectId/scenes/$sceneId'
      path: '/scenes/$sceneId'
      fullPath: '/workspace/$projectId/scenes/$sceneId'
      preLoaderRoute: typeof WorkspaceProjectIdScenesSceneIdRouteImport
      parentRoute: typeof WorkspaceProjectIdRouteRoute
    }
  }
}

interface GalleryRouteRouteChildren {
  GalleryImageIdRoute: typeof GalleryImageIdRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
}

const GalleryRouteRouteChildren: GalleryRouteRouteChildren = {
  GalleryImageIdRoute: GalleryImageIdRoute,
  GalleryIndexRoute: GalleryIndexRoute,
}

const GalleryRouteRouteWithChildren = GalleryRouteRoute._addFileChildren(
  GalleryRouteRouteChildren,
)

interface WorkspaceProjectIdRouteRouteChildren {
  WorkspaceProjectIdIndexRoute: typeof WorkspaceProjectIdIndexRoute
  WorkspaceProjectIdScenesSceneIdRoute: typeof WorkspaceProjectIdScenesSceneIdRoute
}

const WorkspaceProjectIdRouteRouteChildren: WorkspaceProjectIdRouteRouteChildren =
  {
    WorkspaceProjectIdIndexRoute: WorkspaceProjectIdIndexRoute,
    WorkspaceProjectIdScenesSceneIdRoute: WorkspaceProjectIdScenesSceneIdRoute,
  }

const WorkspaceProjectIdRouteRouteWithChildren =
  WorkspaceProjectIdRouteRoute._addFileChildren(
    WorkspaceProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRouteRoute: GalleryRouteRouteWithChildren,
  WorkspaceProjectIdRouteRoute: WorkspaceProjectIdRouteRouteWithChildren,
  BundlesIndexRoute: BundlesIndexRoute,
  GenerateIndexRoute: GenerateIndexRoute,
  MetadataIndexRoute: MetadataIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
